apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-redis
  labels:
    app: spring-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-redis
  template:
    metadata:
      labels:
        app: spring-redis
    spec:
      containers:
      - name: app
        image: nikawang.azurecr.io/javaapp/redis-springboot:v1
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "200m"
        env:
        - name: SERVER_PORT
          value: "8888"
        - name: SPRING_REDIS_HOST
          value: "172.168.59.67"
        - name: SPRING_REDIS_PORT
          value: "6379"
      nodeName: aks-usermode-28744021-vmss000000
